E6Post:
  path: post
  properties:
    id:
      description: " The ID number of the post."
      type: int
    file:
      description: " The post's high-res file info."
      type: PostFile
    preview:
      description: " The post's lower-res preview file info."
      type: PostPreview
    sample:
      description: " The post's sample/thumbnail file info."
      type: PostSample
    score:
      description: " The post's user score."
      type: PostScore
    tags:
      description: " The tags listed on the post."
      type: PostTags
    locked_tags:
      description: " A list of tags that are locked on the post."
      type: array
      items:
        type: string
    change_seq:
      type: int
    flags:
      type: PostFlags
    rating:
      description: " The post's content rating. Either SAFE, EXPLICIT, or QUESTIONABLE."
      type: PostRating
    fav_count:
      description: " How many people have favorited the post."
      type: int
    sources:
      description: " A list of source URL's for the post."
      type: array
      items:
        type: string
    pools:
      description: " An array of Pool IDs that the post is a part of."
      type: array
      items:
        type: int
    relationships:
      type: PostRelationships
    approver_id:
      description: " The ID of the user that approved the post, if available."
      type: int
    uploader_id:
      description: " The ID of the user that uploaded the post."
      type: int
    description:
      description: " The post's description."
      type: string
    comment_count:
      description: " The number of comments on the post."
      type: int
    is_favorited:
      description: " Will return if the authenticated user has favorited the post or not."
      type: bool

PostFile:
  path: post
  properties:
    width:
      description: " The width of the post."
      type: int
    height:
      description: " The height of the post."
      type: int
    ext:
      description: " The file’s extension."
      type: string
    size:
      description: " The size of the file in bytes."
      type: int
    md5:
      description: " The MD5 hash of the file."
      type: string
    url:
      description: " The URL where the file is hosted on E6."
      type: string

PostPreview:
  path: post
  properties:
    width:
      description: " The width of the post preview."
      type: int
    height:
      description: " The height of the post preview."
      type: int
    url:
      description: " The URL where the preview file is hosted on E6."
      type: string

PostSample:
  path: post
  properties:
    has:
      description: " If the post has a sample/thumbnail or not."
      type: bool
    width:
      description: " The width of the post sample."
      type: int
    height:
      description: " The height of the post sample."
      type: int
    url:
      description: " The URL where the sample file is hosted on E6."
      type: string

PostScore:
  path: post
  properties:
    up:
      description: " The number of times voted up."
      type: int
    down:
      description: " A negative number representing the number of times voted down."
      type: int
    total:
      description: " The total score (up + down)."
      type: int

PostTags:
  path: post
  properties:
    general:
      description: " An array of all the general tags on the post."
      type: array
      items:
        type: string
    species:
      description: " An array of all the species tags on the post."
      type: array
      items:
        type: string
    character:
      description: " An array of all the character tags on the post."
      type: array
      items:
        type: string
    artist:
      description: " An array of all the artist tags on the post."
      type: array
      items:
        type: string
    invalid:
      description: " An array of all the invalid tags on the post."
      type: array
      items:
        type: string
    lore:
      description: " An array of all the lore tags on the post."
      type: array
      items:
        type: string
    meta:
      description: " An array of all the meta tags on the post."
      type: array
      items:
        type: string

PostFlags:
  path: post
  properties:
    pending:
      description: " If the post is pending approval."
      type: bool
    flagged:
      description: " If the post is flagged for deletion."
      type: bool
    note_locked:
      description: " If the post has its notes locked."
      type: bool
    status_locked:
      description: " If the post's status has been locked."
      type: bool
    rating_locked:
      description: " If the post's rating has been locked."
      type: bool
    deleted:
      description: " If the post has been deleted."
      type: bool

PostRating:
  path: post
  type: enum
  generate_map: true
  generate_extensions: true
  properties:
    SAFE:
      description: " The post should be safe for work."
      value: s
    EXPLICIT:
      description: " The post is riding the line making it NSFW."
      value: e
    QUESTIONABLE:
      description: " The post is straight up NSFW."
      value: q

PostRelationships:
  path: post
  properties:
    parent_id:
      description: " The ID of the post's parent, if it has one."
      type: int
    has_children:
      description: " If the post has child posts."
      type: bool
    has_active_children:
      type: bool
    children:
      description: " A list of child post IDs that are linked to the post, if it has any."
      type: array
      items:
        type: int

PostResponse:
  path: post
  properties:
    posts:
      description: " The actual posts!"
      type: array
      items:
        type: E6Post

AutocompleteTag:
  path: autocomplete
  properties:
    id:
      type: int
    name:
      type: string
    post_count:
      type: int
    category:
      type: int
    antecedent_name:
      type: string